### ISSUE TITLE
Installation from CurseForge not working

### ISSUE THREAD

**Issue by Krutoy242** [igentuman/BlockBooster#6]
Using CurseForge launcher, I installed BlockBooster into my 1.12.2 modpack.

The error i got in logs:
```less
[Client thread/ERROR] [FML]: Unable to read a class file correctly
[Client thread/ERROR] [FML]: There was a problem reading the entry igentuman/blockbooster/block/BlockBoosterMana$1.class in the jar E:\mc_client\GDLuncher\instances\E2E-E\minecraft\mods\BlockBooster-1.19.2-1.0.4.jar - probably a corrupt zip
```

I believe, that `BlockBooster-1.19.2-1.0.4.jar` is wrong jar 😄

**Comment by igentuman** [comment]
I've just re-checked file on curseforge. Everything is fine. Supported versions for this file defined correctly.
Issue related to cursedforge launcher.
